version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=klugcode
      - POSTGRES_USER=klugcode
      - POSTGRES_PASSWORD=klugcode123
  web:
    build: klugcode
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db