# Generated by Django 5.0.2 on 2024-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="websites",
            field=models.URLField(null=True),
        ),
    ]
