# Generated by Django 5.0.2 on 2024-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_alter_idea_websites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="websites",
            field=models.URLField(blank=True, null=True),
        ),
    ]
