# Generated by Django 5.0.2 on 2024-03-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_websites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Comment',
        ),
    ]
